site_name: Kroki Plugin Playground
docs_dir: docs


plugins:
  - search
  - kroki:
      fence_prefix: ''
      http_method: POST
      diagram_background_color_light: "#f8f8f8"
      diagram_background_color_dark: "#999696"
  - techdocs-core

nav:
  - Home: index.md
  - Diagrams:
      - Sequence & Activity: diagrams.md
      - Network & Infrastructure: network.md
      - UML & Class Diagrams: uml.md
